plugins {
    id 'com.android.application'
}

android {
    namespace 'com.mini.patternshortcut'
    compileSdk 35

    defaultConfig {
        applicationId "com.mini.patternshortcut"
        minSdk 26
        targetSdk 35
        versionCode 1
        versionName "1.0.0"
    }
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(17)
    }
}
